CREATE TABLE categories
(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name MEDIUMTEXT NOT NULL,
    title TEXT NOT NULL,
    level TINYINT NOT NULL,
    parent_category_id INT NULL,
    created_at DATETIME  DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME  DEFAULT CURRENT_TIMESTAMP
);