CREATE TABLE IF NOT EXISTS  templates
(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    path VARCHAR(255) NOT NULL UNIQUE,
    type VARCHAR(255) NOT NULL,
    thumbnail_media_id BIGINT UNSIGNED,
    created_at DATETIME  DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME  DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(thumbnail_media_id) REFERENCES media(id)
);