CREATE TABLE IF NOT EXISTS categories
(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name MEDIUMTEXT NOT NULL,
    title TEXT NULL,
    level TINYINT(10) NOT NULL,
    display_order INT NULL,
    parent_category_id INT NULL,
    visibility TINYINT(2) DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    );
