CREATE TABLE  IF NOT EXISTS   %tbl_name%
(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    connector_id INT NOT NULL,
    user_id INT NOT NULL,
    created_at DATETIME  DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME  DEFAULT CURRENT_TIMESTAMP
);